name: Build Docker Image, Generate SBOM, and Run SAST

on:
  push:
    branches:
      - master  # Ana branch "master" olarak güncellendi
  pull_request:
    branches:
      - master

jobs:
  build-and-sbom:
    name: Build Docker Image and Generate SBOM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t mebezir-juice-shop .

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM with Syft
        run: |
          syft docker:mebezir-juice-shop -o cyclonedx-json > sbom.json

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: juice-shop-sbom
          path: sbom.json

  semgrep-sast:
    name: Run Semgrep SAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: |
          curl -sL https://semgrep.dev/install.sh | bash

      - name: Run Semgrep SAST Scan
        run: |
          semgrep scan --config auto --sarif --output semgrep-results.sarif

      - name: Upload Semgrep SARIF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif
          path: semgrep-results.sarif
